services:
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
    depends_on:
      - redis
    ports:
      - "8081:8081"
    networks:
      - zapdiviser

  redis:
    ports:
      - 6379:6379

  minio:
    ports:
      - 9000:9000
      - 9001:9001

  soketi:
    ports:
      - 6001:6001
