services:
  frontend:
    build:
      context: ./frontend
    expose:
      - 8080:8080
    networks:
      - caddy
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: backend.${HOST}
    labels:
      caddy: ${HOST}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    deploy:
      labels:
        caddy: ${HOST}
        caddy.reverse_proxy: "{{upstreams 8080}}"

  backend:
    build:
      context: ./backend
    expose:
      - 8000:8000
    networks:
      - local
      - caddy
    depends_on:
      - db
      - redis
      - minio
    env_file:
      - .env
    labels:
      caddy: backend.${HOST}
      caddy.reverse_proxy: "{{upstreams 8000}}"
    deploy:
      labels:
        caddy: backend.${HOST}
        caddy.reverse_proxy: "{{upstreams 8000}}"
