services:
  frontend:
    build:
      context: ./frontend
    expose:
      - 3000:3000
    networks:
      - local
      - caddy
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: backend.${HOST}
    labels:
      caddy: ${HOST}, www.${HOST}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    deploy:
      labels:
        caddy: ${HOST}, www.${HOST}
        caddy.reverse_proxy: "{{upstreams 3000}}"

  backend:
    build:
      context: ./backend
    expose:
      - 8000:8000
    networks:
      - local
      - caddy
    depends_on:
      - db
      - redis
      - minio
    env_file:
      - path: .env
        required: false
      - path: stack.env
        redirect: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy_0: backend.${HOST}
      caddy_0.reverse_proxy: "{{upstreams 8000}}"
      caddy_1: webhook.${HOST}
      caddy_1.rewrite: "* /api/product/webhook{uri}"
      caddy_1.reverse_proxy: "{{upstreams 8000}}"
      caddy_2: redirect.${HOST}
      caddy_2.rewrite: "* /api/product/redirect{uri}"
      caddy_2.reverse_proxy: "{{upstreams 8000}}"
      caddy_3: admin.${HOST}
      caddy_3.rewrite: "* /admin-br{uri}"
      caddy_3.reverse_proxy: "{{upstreams 8000}}"
    deploy:
      labels:
        caddy_0: backend.${HOST}
        caddy_0.reverse_proxy: "{{upstreams 8000}}"
        caddy_1: webhook.${HOST}
        caddy_1.rewrite: "* /api/product/webhook{uri}"
        caddy_1.reverse_proxy: "{{upstreams 8000}}"
        caddy_2: redirect.${HOST}
        caddy_2.rewrite: "* /api/product/redirect{uri}"
        caddy_2.reverse_proxy: "{{upstreams 8000}}"
        caddy_3: admin.${HOST}
        caddy_3.rewrite: "* /admin-br{uri}"
        caddy_3.reverse_proxy: "{{upstreams 8000}}"
