services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  minio:
    networks:
      - caddy
    labels:
      caddy_0: minio-api.${HOST}
      caddy_0.reverse_proxy: "{{upstreams 9000}}"
      caddy_1: minio.${HOST}
      caddy_1.reverse_proxy: "{{upstreams 9001}}"

  migrate:
    build:
      context: ./backend
    depends_on:
      - db
    networks:
      - internal
    command: ["sh", "-c", "node ./node_modules/typeorm/cli -d ./dist/ormconfig.js migration:run"]
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build:
      context: ./frontend
    command: --brotli
    networks:
      - internal
      - caddy
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: backend.${HOST}
    labels:
      caddy_0: app.${HOST}
      caddy_0.reverse_proxy: "{{upstreams 8080}}"
      caddy_1: ${HOST}
      caddy_1.rewrite: "* /zapdiviser{uri}"
      caddy_1.reverse_proxy: https://contingenciainfinita.com
      caddy_1.reverse_proxy.0_header_up: Host contingenciainfinita.com
      caddy_1.reverse_proxy.1_header_up: Alt-Used contingenciainfinita.com
      caddy_2: www.${HOST}
      caddy_2.redir: https://${HOST}{uri}

  backend:
    build:
      context: ./backend
    networks:
      - internal
      - caddy
    depends_on:
      - db
      - redis
      - minio
    environment:
      HOST: ${HOST}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy_0: backend.${HOST}
      caddy_0.reverse_proxy: "{{upstreams 8000}}"
      caddy_1: webhook.${HOST}
      caddy_1.rewrite: "* /api/product/webhook{uri}"
      caddy_1.reverse_proxy: "{{upstreams 8000}}"
      caddy_2: redirect.${HOST}
      caddy_2.rewrite: "* /api/redirects{uri}"
      caddy_2.reverse_proxy: "{{upstreams 8000}}"
      caddy_3: admin.${HOST}
      caddy_3.redir: "/ /admin-br"
      caddy_3.reverse_proxy: "{{upstreams 8000}}"

networks:
  caddy:
    external: true

volumes:
  caddy_data:
