version: "3.9"

name: zapdiviser

services:
  db:
    image: postgres:alpine
    ports:
      - 5433:5432
    networks:
      - internal
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - internal
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis:/data

  minio:
    image: minio/minio
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    networks:
      - internal
    command: server /data --console-address :9001
    restart: unless-stopped

  setup-minio:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - internal
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc alias set minio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}
        mc admin user svcacct add minio ${MINIO_USER} --access-key ${MINIO_ACCESS_KEY} --secret-key ${MINIO_SECRET_KEY}
        mc mb minio/zapdiviser

networks:
  internal:

volumes:
  redis:
  postgres:
  minio:
