name: code

services:
  db:
    image: postgres:alpine
    ports:
      - 5433:5432
    networks:
      - zapdiviser
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    networks:
      - zapdiviser
    volumes:
      - redis:/redis
    command: redis-server --requirepass ${REDIS_PASSWORD}

  minio:
    image: minio/minio
    volumes:
      - "minio:/data"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    networks:
      - zapdiviser
    command: server /data --console-address :9001

  setup-minio:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - zapdiviser
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc alias set minio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}
        mc admin user svcacct add minio ${MINIO_USER} --access-key ${MINIO_ACCESS_KEY} --secret-key ${MINIO_SECRET_KEY}
        mc mb minio/zapdiviser
        mc mb minio/backups

  soketi:
    image: quay.io/soketi/soketi:1.0-16-distroless
    environment:
      SOKETI_DEFAULT_APP_ID: zapdiviser
      SOKETI_DEFAULT_APP_KEY: ${VITE_SOKETI_APP_KEY}
      SOKETI_DEFAULT_APP_SECRET: ${SOKETI_APP_SECRET}
    networks:
      - zapdiviser

  migrate:
    build:
      context: .
      target: backend
    depends_on:
      - db
    networks:
      - zapdiviser
    command: ["sh", "-c", "node ./node_modules/typeorm/cli -d ./dist/ormconfig.js migration:run"]
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  zapdiviser:
    external: true

volumes:
  redis:
  postgres:
  minio:
