version: "3.9"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  db:
    image: postgres:alpine
    networks:
      - internal
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  migrate:
    build:
      context: ./backend
    depends_on:
      - db
    networks:
      - internal
    command: ["sh", "-c", "node ./node_modules/typeorm/cli -d ./dist/ormconfig.js migration:run"]
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis:/data

  minio:
    image: minio/minio
    volumes:
      - "minio:/data"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    networks:
      - internal
      - caddy
    command: server /data --console-address :9001
    restart: unless-stopped
    labels:
      caddy_0: minio-api.${HOST}
      caddy_0.reverse_proxy: "{{upstreams 9000}}"
      caddy_1: minio.${HOST}
      caddy_1.reverse_proxy: "{{upstreams 9001}}"

  setup-minio:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - internal
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc alias set minio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}
        mc admin user svcacct add minio ${MINIO_USER} --access-key ${MINIO_ACCESS_KEY} --secret-key ${MINIO_SECRET_KEY}
        mc mb minio/zapdiviser

networks:
  caddy:
    external: true
  internal:

volumes:
  caddy_data:
  redis:
  postgres:
  minio:
