services:
  frontend:
    build:
      context: ./frontend
    expose:
      - 3000:3000
    networks:
      - local
      - caddy
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: backend.${HOST}
    labels:
      caddy: ${HOST}, www.${HOST}
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.rewrite: "* /"
    deploy:
      labels:
        caddy: ${HOST}, www.${HOST}
        caddy.reverse_proxy: "{{upstreams 3000}}"
        caddy.rewrite: "* /"

  backend:
    build:
      context: ./backend
    expose:
      - 8000:8000
    networks:
      - local
      - caddy
    depends_on:
      - db
      - redis
      - minio
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy: backend.${HOST}
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy_webhook: webhook.${HOST}
      caddy_webhook.rewrite: "* /api/product{uri}"
      caddy_webhook.reverse_proxy: {{upstreams 8000}}
    deploy:
      labels:
        caddy: backend.${HOST}
        caddy.reverse_proxy: "{{upstreams 8000}}"
        caddy_webhook: webhook.${HOST}
        caddy_webhook.rewrite: "* /api/product{uri}"
        caddy_webhook.reverse_proxy: "{{upstreams 8000}}""
